### ISSUE TITLE
Add option to choose/specify date format

### ISSUE THREAD

**Issue by lemiii** [RichardSlater/atom-random#2]
Not all systems/frameworks are compatible with the chance.date() format resulting in 'Sun Feb 09 2059 09:07:52 GMT-0500 (EST)' 

Add an option to permit specifying a date in other common formats such as [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) or a Unix timestamp.

**Comment by RichardSlater** [comment]
Great idea, thanks I'll take a look.

**Comment by lemiii** [comment]
I've created a fork of it, but uncertain how to test it within atom. I've never made an atom package before. I see you already have timestamp, so i added `random isodate`

https://github.com/lemiii/atom-random

**Comment by RichardSlater** [comment]
Thanks! To test this you need to:
1. uninstall the published module
2. open a command line and type `apm link <path to repository>`
3. restart atom either by closing or opening or by selecting `Window: Reload` from the Command Palette

Once you have done all of this you should see your local changes within Atom, each time you make a code change you will need to issue a `Window: Reload` command as Node doesn't support hot swapping code out.

**Comment by lemiii** [comment]
Sweet. Got it working and spitting out random isodate values. It shows up in the menu as well!

**Comment by lemiii** [comment]
Okay, fun learning experience. Pull request setup and all tests passing. If accepted, this will be a first for me. Thanks for the patience and direction.

**Comment by RichardSlater** [comment]
@lemiii the pull request has been merged and the Atom packaged has been published as `1.1.0` to atom.io.  Thanks for your work on this.
